version: '3.5'
services:
  postgres:
    image: postgres:13.4-alpine
    container_name: fastify-slonik
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    ports:
      - 5432:5432
    volumes:
      - ./fixtures/init.sql:/docker-entrypoint-initdb.d/init.sql
