version: '3.5'
services:
  postgres:
    image: postgres
    container_name: fastify-slonik
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      docker_net:
        ipv4_address: 172.22.0.100
networks:
  docker_net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16