name: Validate & Release
on:
  push:
    tags:
      - v*
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      DB_USER: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DATABASE_URL: postgres://postgres:postgres@0.0.0.0:5432/postgres?sslmode=disable

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    name: Node.js ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - run: docker-compose up -d
      - run: npm test

  publish-npm:
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 18.x
        registry-url: https://registry.npmjs.org/
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
